/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CreateOrderDialog: typeof import('./src/components/business/CreateOrderDialog.vue')['default']
    DashboardShell: typeof import('./src/components/dashboard/DashboardShell.vue')['default']
    DashboardToolbar: typeof import('./src/components/dashboard/DashboardToolbar.vue')['default']
    DynamicForm: typeof import('./src/components/business/DynamicForm.vue')['default']
    EnterpriseFormDrawer: typeof import('./src/components/business/EnterpriseFormDrawer.vue')['default']
    FlowDesigner: typeof import('./src/components/business/FlowDesigner.vue')['default']
    FlowRecords: typeof import('./src/components/business/FlowRecords.vue')['default']
    FormDesigner: typeof import('./src/components/business/FormDesigner.vue')['default']
    NodePropertyPanel: typeof import('./src/components/business/NodePropertyPanel.vue')['default']
    OrderProgress: typeof import('./src/components/business/OrderProgress.vue')['default']
    PersonSelector: typeof import('./src/components/business/PersonSelector.vue')['default']
    PlaceholderWidget: typeof import('./src/components/business/PlaceholderWidget.vue')['default']
    PositionSwitcher: typeof import('./src/components/base/PositionSwitcher.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusTag: typeof import('./src/components/business/StatusTag.vue')['default']
    ThemeToggle: typeof import('./src/components/base/ThemeToggle.vue')['default']
    WidgetCard: typeof import('./src/components/dashboard/WidgetCard.vue')['default']
    WidgetGrid: typeof import('./src/components/dashboard/WidgetGrid.vue')['default']
    WidgetRenderer: typeof import('./src/components/dashboard/WidgetRenderer.vue')['default']
  }
}
