/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppIcon: typeof import('./src/components/base/AppIcon.vue')['default']
    CreateOrderDialog: typeof import('./src/components/business/CreateOrderDialog.vue')['default']
    DashboardShell: typeof import('./src/components/dashboard/DashboardShell.vue')['default']
    DashboardToolbar: typeof import('./src/components/dashboard/DashboardToolbar.vue')['default']
    DynamicForm: typeof import('./src/components/business/DynamicForm.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElStep: typeof import('element-plus/es')['ElStep']
    ElSteps: typeof import('element-plus/es')['ElSteps']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTree: typeof import('element-plus/es')['ElTree']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    EnterpriseFormDrawer: typeof import('./src/components/business/EnterpriseFormDrawer.vue')['default']
    EnterpriseSwitcher: typeof import('./src/components/base/EnterpriseSwitcher.vue')['default']
    FlowDesigner: typeof import('./src/components/business/FlowDesigner.vue')['default']
    FlowRecords: typeof import('./src/components/business/FlowRecords.vue')['default']
    FormDesigner: typeof import('./src/components/business/FormDesigner.vue')['default']
    GisMapPicker: typeof import('./src/components/business/GisMapPicker.vue')['default']
    NodePropertyPanel: typeof import('./src/components/business/NodePropertyPanel.vue')['default']
    OperationLogsTab: typeof import('./src/components/business/OperationLogsTab.vue')['default']
    OrderProgress: typeof import('./src/components/business/OrderProgress.vue')['default']
    PermissionConfigDrawer: typeof import('./src/components/business/PermissionConfigDrawer.vue')['default']
    PersonSelector: typeof import('./src/components/business/PersonSelector.vue')['default']
    PlaceholderWidget: typeof import('./src/components/business/PlaceholderWidget.vue')['default']
    PositionSelect: typeof import('./src/components/business/PositionSelect.vue')['default']
    PositionSwitcher: typeof import('./src/components/base/PositionSwitcher.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusTag: typeof import('./src/components/business/StatusTag.vue')['default']
    TableFilterPopover: typeof import('./src/components/base/TableFilterPopover.vue')['default']
    TableSortIcon: typeof import('./src/components/base/TableSortIcon.vue')['default']
    ThemeToggle: typeof import('./src/components/base/ThemeToggle.vue')['default']
    WidgetCard: typeof import('./src/components/dashboard/WidgetCard.vue')['default']
    WidgetGrid: typeof import('./src/components/dashboard/WidgetGrid.vue')['default']
    WidgetRenderer: typeof import('./src/components/dashboard/WidgetRenderer.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
